name: "Build doc-sync prompt"
description: "Render the Codex prompt with repo metadata, scope, and commit summary."
inputs:
  base_ref:
    description: "Base branch reference for the PR"
    required: true
  head_ref:
    description: "Head branch reference"
    required: true
  pr_number:
    description: "Pull request number"
    required: true
  repository:
    description: "owner/repo string"
    required: true
  report_path:
    description: "Path to the doc-sync report file"
    required: true
  template_path:
    description: "Path to the prompt template"
    required: true
  doc_globs_path:
    description: "File containing doc glob patterns"
    required: true
  prompt_path:
    description: "Destination file for the rendered prompt"
    required: true
  commits_path:
    description: "Path to the commit summary file"
    required: true
  shared_path:
    description: "Path to the shared workflow checkout"
    required: true
runs:
  using: "composite"
  steps:
    - uses: ../../actions/doc-sync/build-prompt
      with:
        base_ref: ${{ inputs.base_ref }}
        head_ref: ${{ inputs.head_ref }}
        pr_number: ${{ inputs.pr_number }}
        repository: ${{ inputs.repository }}
        report_path: ${{ inputs.report_path }}
        doc_globs_path: ${{ inputs.doc_globs_path }}
        prompt_path: ${{ inputs.prompt_path }}
        commits_path: ${{ inputs.commits_path }}
        template_path: ${{ inputs.template_path }}
