name: "Format Codex issue-plan comment"
description: "Convert Codex JSON output into a markdown issue comment and expose it for posting."
inputs:
  output-path:
    description: "Path to the Codex JSON output file."
    required: false
    default: "codex-output.json"
  issue-number:
    description: "Issue number being commented on (for metadata section)."
    required: false
    default: ""
  issue-url:
    description: "Issue URL for link rendering."
    required: false
    default: ""
  issue-title:
    description: "Issue title shown in the comment header."
    required: false
    default: ""
  comment-path:
    description: "Destination markdown file for the rendered comment."
    required: false
    default: "issue-plan-comment.md"
  payload-path:
    description: "Destination JSON payload (body wrapper)."
    required: false
    default: "issue-plan-comment.json"
outputs:
  summary:
    description: "Summary string returned by Codex."
    value: ${{ steps.format.outputs.summary }}
  plan_markdown:
    description: "Plan markdown string returned by Codex."
    value: ${{ steps.format.outputs.plan_markdown }}
  comment_path:
    description: "Markdown file containing the rendered comment."
    value: ${{ steps.format.outputs.comment_path }}
  comment_payload_path:
    description: "JSON payload file suitable for gh api."
    value: ${{ steps.format.outputs.comment_payload_path }}
runs:
  using: "composite"
  steps:
    - id: format
      shell: bash
      env:
        OUTPUT_PATH: ${{ inputs.output-path }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        ISSUE_URL: ${{ inputs.issue-url }}
        ISSUE_TITLE: ${{ inputs.issue-title }}
        COMMENT_PATH: ${{ inputs.comment-path }}
        PAYLOAD_PATH: ${{ inputs.payload-path }}
      run: |
        set -euo pipefail
        if [ ! -f "$OUTPUT_PATH" ]; then
          echo "::error::Missing Codex output at $OUTPUT_PATH" >&2
          exit 1
        fi
        python3 "$GITHUB_ACTION_PATH/render.py"
