name: "Codex Unified Workflows"
description: "Single GitHub Action that exposes all Codex-powered workflows (review, go-tests, release, auto-label, doc-sync)."
author: "activadee"
branding:
  icon: "command"
  color: "purple"
inputs:
  command:
    description: "Workflow command to execute (review | go-tests | release | auto-label | doc-sync)."
    required: true
  prompt_path:
    description: "Optional prompt file override for Codex-aware commands. Defaults depend on the command."
    required: false
  prompt_extra:
    description: "Additional markdown appended to the review prompt (review command only)."
    required: false
  model:
    description: "Codex model override passed to codex exec."
    required: false
  effort:
    description: "Codex reasoning effort override."
    required: false
  codex_args:
    description: "Additional arguments forwarded to codex exec (shell string)."
    required: false
  codex_bin:
    description: "Path to the codex CLI binary (default: codex)."
    required: false
  event_path:
    description: "Path to a GitHub event payload JSON file (auto-label/review/doc-sync fallback)."
    required: false
  pull_number:
    description: "Explicit pull request number override for review/doc-sync commands."
    required: false
  dry_run:
    description: "When true, commands will print output without mutating GitHub state (where supported)."
    required: false
    default: "false"
  go_version:
    description: "Go version to install for go-tests/release commands (e.g. 1.22.5)."
    required: false
  go_version_file:
    description: "Path to file that declares the Go version (default: go.mod)."
    required: false
  working_directory:
    description: "Working directory for go-tests."
    required: false
  test_flags:
    description: "Flags forwarded to go test (default: ./...)."
    required: false
  pre_test:
    description: "Shell snippet executed before go test runs."
    required: false
  env:
    description: "Multiline list of KEY=VALUE pairs forwarded to go test."
    required: false
  tag_name:
    description: "Release tag (release command only)."
    required: false
  release_title:
    description: "Release display title (release command)."
    required: false
  target:
    description: "Git ref used for the release (default: main)."
    required: false
    default: "main"
  draft:
    description: "If true, create release as draft."
    required: false
    default: "false"
  skip_tests:
    description: "Skip Go test execution inside the release command."
    required: false
    default: "false"
  notes_extra:
    description: "Extra markdown appended to the release note context."
    required: false
  commit_limit:
    description: "Number of commits to feed into Codex when generating release notes (default 50)."
    required: false
    default: "50"
  max_labels:
    description: "Maximum labels applied by auto-label (1-3)."
    required: false
    default: "3"
  doc_globs:
    description: "Multiline glob list describing documentation scope (doc-sync only)."
    required: false
  doc_globs_file:
    description: "Path where doc globs manifest will be written (doc-sync)."
    required: false
    default: "doc-globs.txt"
  prompt_template:
    description: "Doc-sync prompt template override (default .github/prompts/codex-doc-sync.md)."
    required: false
  report_path:
    description: "Doc-sync report output path."
    required: false
    default: "doc-sync-report.md"
  commits_path:
    description: "File where doc-sync commit summary is stored."
    required: false
    default: "doc-commits.md"
  patch_path:
    description: "Doc-sync git patch output path."
    required: false
    default: "doc-changes.patch"
  files_path:
    description: "Doc-sync touched file list output path."
    required: false
    default: "doc-changes.txt"
  base_ref:
    description: "Base branch override for doc-sync."
    required: false
  head_ref:
    description: "Head branch override for doc-sync."
    required: false
  head_sha:
    description: "Head commit SHA override for doc-sync."
    required: false
  safety_strategy:
    description: "Codex safety strategy used by review/doc-sync commands."
    required: false
  auto_commit:
    description: "Toggle automatic git commit for doc-sync (default true)."
    required: false
    default: "true"
  auto_push:
    description: "Toggle automatic git push for doc-sync (default true)."
    required: false
    default: "true"
  comment:
    description: "Toggle PR comment posting for doc-sync (default true)."
    required: false
    default: "true"
outputs: {}
runs:
  using: "node20"
  main: "dist/action.cjs"
