name: "Collect Codex Review Inputs"
description: "Fetch diff, existing comments, review threads, and other metadata required for Codex review."
inputs:
  github-token:
    description: "GitHub token with repo scope"
    required: true
runs:
  using: "composite"
  steps:
    - name: Collect review context
      uses: ../../actions/codex-review/collect-context
      with:
        github-token: ${{ inputs.github-token }}
