name: "Prepare doc-sync workspace"
description: "Ignore helper files, fetch the base ref, and build the documentation scope + commit summary."
inputs:
  base_ref:
    description: "Base branch ref to fetch (e.g., main)."
    required: true
  head_sha:
    description: "Head SHA used for logging."
    required: false
    default: ""
  doc_report_path:
    description: "Path to the markdown summary file."
    required: true
  doc_commits_path:
    description: "File where the commit list will be written."
    required: true
  doc_globs_file:
    description: "File where doc globs will be persisted."
    required: true
  doc_globs:
    description: "Newline-separated glob list that defines documentation files."
    required: false
    default: |
      docs/**
      **/*.md
      README*
runs:
  using: "composite"
  steps:
    - name: Ignore helper artifacts
      shell: bash
      env:
        INPUT_DOC_REPORT_PATH: ${{ inputs.doc_report_path }}
        INPUT_DOC_COMMITS_PATH: ${{ inputs.doc_commits_path }}
        INPUT_DOC_GLOBS_FILE: ${{ inputs.doc_globs_file }}
      run: |
        mkdir -p .git/info
        cat <<EOF | while read -r path; do
        ${INPUT_DOC_REPORT_PATH}
        ${INPUT_DOC_COMMITS_PATH}
        ${INPUT_DOC_GLOBS_FILE}
        codex_prompt.md
        __codex_shared
        EOF
          if [ -n "$path" ] && ! grep -qx "$path" .git/info/exclude 2>/dev/null; then
            echo "$path" >> .git/info/exclude
          fi
        done

    - name: Fetch base ref and collect commit summary
      shell: bash
      env:
        BASE_REF: ${{ inputs.base_ref }}
        COMMITS_PATH: ${{ inputs.doc_commits_path }}
        HEAD_SHA: ${{ inputs.head_sha }}
      run: |
        git fetch --no-tags origin "$BASE_REF"
        git log --no-merges --pretty=format:'- %s (%h)' origin/$BASE_REF..HEAD > "$COMMITS_PATH"
        if [ ! -s "$COMMITS_PATH" ]; then
          echo "- No commits detected between origin/$BASE_REF and ${HEAD_SHA:-HEAD}." > "$COMMITS_PATH"
        fi

    - name: Write documentation scope manifest
      shell: bash
      env:
        DOC_GLOBS: ${{ inputs.doc_globs }}
        DOC_GLOBS_PATH: ${{ inputs.doc_globs_file }}
        ACTION_ROOT: ${{ github.action_path }}
      run: |
        node "$ACTION_ROOT/../lib/write_doc_globs.js"
