name: "Resolve doc-sync pull request context"
description: "Fetch PR metadata (base/head refs) and ensure the head branch lives in the same repository."
inputs:
  github-token:
    description: "GitHub token with repo scope"
    required: true
outputs:
  proceed:
    description: "Whether the workflow should continue."
    value: ${{ steps.delegate.outputs.proceed }}
  number:
    description: "Pull request number."
    value: ${{ steps.resolve.outputs.number }}
  base_ref:
    description: "Base branch ref."
    value: ${{ steps.resolve.outputs.base_ref }}
  head_ref:
    description: "Head branch ref."
    value: ${{ steps.resolve.outputs.head_ref }}
  head_sha:
    description: "Head commit SHA."
    value: ${{ steps.resolve.outputs.head_sha }}
  repository:
    description: "owner/repo string."
    value: ${{ steps.delegate.outputs.repository }}
  proceed_reason:
    description: "Reason provided when doc sync is skipped."
    value: ${{ steps.delegate.outputs.proceed_reason }}
runs:
  using: "composite"
  steps:
    - id: delegate
      uses: ../../actions/doc-sync/context
      with:
        github-token: ${{ inputs.github-token }}
