name: "Resolve doc-sync pull request context"
description: "Fetch PR metadata (base/head refs) and ensure the head branch lives in the same repository."
inputs:
  github-token:
    description: "GitHub token with repo scope"
    required: true
outputs:
  proceed:
    description: "Whether the workflow should continue."
    value: ${{ steps.resolve.outputs.proceed }}
  number:
    description: "Pull request number."
    value: ${{ steps.resolve.outputs.number }}
  base_ref:
    description: "Base branch ref."
    value: ${{ steps.resolve.outputs.base_ref }}
  head_ref:
    description: "Head branch ref."
    value: ${{ steps.resolve.outputs.head_ref }}
  head_sha:
    description: "Head commit SHA."
    value: ${{ steps.resolve.outputs.head_sha }}
  repository:
    description: "owner/repo string."
    value: ${{ steps.resolve.outputs.repository }}
  proceed_reason:
    description: "Reason provided when doc sync is skipped."
    value: ${{ steps.resolve.outputs.proceed_reason }}
runs:
  using: "composite"
  steps:
    - id: resolve
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const repoFull = `${owner}/${repo}`;

          let pr = context.payload.pull_request;
          if (!pr && context.payload.issue?.pull_request) {
            const response = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: context.payload.issue.number,
            });
            pr = response.data;
          }

          if (!pr) {
            core.setOutput('proceed', 'false');
            core.setOutput('proceed_reason', 'No pull request payload available.');
            core.info('Doc sync skipped: no pull request context found.');
            return;
          }

          const headRepoFull = pr.head?.repo?.full_name || '';
          const sameRepo = headRepoFull === repoFull;
          if (!sameRepo) {
            core.info(`Doc sync skipped: head repository ${headRepoFull || '(unknown)'} differs from ${repoFull}.`);
            core.setOutput('proceed', 'false');
            core.setOutput('proceed_reason', 'Head repository differs from base repository.');
          } else {
            core.setOutput('proceed', 'true');
            core.setOutput('proceed_reason', 'ready');
          }

          core.setOutput('number', String(pr.number));
          core.setOutput('base_ref', pr.base?.ref || '');
          core.setOutput('head_ref', pr.head?.ref || '');
          core.setOutput('head_sha', pr.head?.sha || '');
          core.setOutput('repository', repoFull);
