name: "Prepare doc-sync workspace"
description: "Ignore helper files, fetch the base ref, and build the documentation scope + commit summary."
inputs:
  base_ref:
    description: "Base branch ref to fetch (e.g., main)."
    required: true
  head_sha:
    description: "Head SHA used for logging."
    required: false
    default: ""
  doc_report_path:
    description: "Path to the markdown summary file."
    required: true
  doc_commits_path:
    description: "File where the commit list will be written."
    required: true
  doc_globs_file:
    description: "File where doc globs will be persisted."
    required: true
  doc_globs:
    description: "Newline-separated glob list that defines documentation files."
    required: false
    default: |
      docs/**
      **/*.md
      README*
  shared_path:
    description: "Path where the shared workflows repository was checked out."
    required: true
runs:
  using: "composite"
  steps:
    - uses: ../../actions/doc-sync/prepare
      with:
        base_ref: ${{ inputs.base_ref }}
        head_sha: ${{ inputs.head_sha }}
        doc_report_path: ${{ inputs.doc_report_path }}
        doc_commits_path: ${{ inputs.doc_commits_path }}
        doc_globs_file: ${{ inputs.doc_globs_file }}
        doc_globs: ${{ inputs.doc_globs }}
