name: "Run Codex auto-labeling"
description: "Invoke Codex to suggest labels for an issue."
inputs:
  codex-auth-json-b64:
    description: "Base64 encoded Codex auth.json"
    required: true
  prompt-path:
    description: "Prompt file path."
    required: false
    default: "codex_prompt.md"
  output-path:
    description: "Destination for Codex JSON output."
    required: false
    default: "codex-output.json"
  output-schema:
    description: "JSON schema describing expected Codex output."
    required: true
  safety-strategy:
    description: "Codex sandbox strategy."
    required: false
    default: "drop-sudo"
  model:
    description: "Optional Codex model override."
    required: false
    default: "gpt-5.1-mini"
  effort:
    description: "Optional reasoning effort override."
    required: false
    default: "medium"
  codex-args:
    description: "Additional CLI args forwarded to Codex."
    required: false
    default: ""
outputs:
  output_path:
    description: "Path to the Codex output JSON."
    value: ${{ inputs.output-path }}
runs:
  using: "composite"
  steps:
    - name: Run Codex auto-label
      uses: activadee/codex-action@main
      with:
        codex-auth-json-b64: ${{ inputs.codex-auth-json-b64 }}
        prompt-file: ${{ inputs.prompt-path }}
        output-file: ${{ inputs.output-path }}
        output-schema: ${{ inputs.output-schema }}
        safety-strategy: ${{ inputs.safety-strategy }}
        model: ${{ inputs.model }}
        effort: ${{ inputs.effort }}
        codex-args: ${{ inputs.codex-args }}
