name: "Run Codex doc sync"
description: "Invoke Codex with the doc-sync prompt and let Codex update, commit, and push documentation changes."
inputs:
  codex-auth-json-b64:
    description: "Base64-encoded Codex auth.json"
    required: true
  prompt-path:
    description: "Path to the prompt markdown file"
    required: false
    default: "codex_prompt.md"
  output-path:
    description: "Path where Codex output JSON should be written"
    required: false
    default: "codex-output.json"
  output-schema:
    description: "JSON schema controlling the Codex response"
    required: true
  safety-strategy:
    description: "Codex sandbox mode"
    required: false
    default: "drop-sudo"
  model:
    description: "Optional Codex model override"
    required: false
    default: "gpt-5.1-mini"
  effort:
    description: "Optional Codex reasoning effort"
    required: false
    default: ""
  codex-args:
    description: "Additional arguments forwarded to codex exec"
    required: false
    default: ""
  pass-through-env:
    description: "Comma or newline separated env vars that should be forwarded to Codex (e.g., GH_TOKEN)."
    required: false
    default: ""
outputs:
  output_path:
    description: "Path to the Codex output file"
    value: ${{ inputs.output-path }}
  summary:
    description: "Short summary of what Codex did."
    value: ${{ steps.parse.outputs.summary }}
  changes_committed:
    description: "\"true\" when Codex committed and pushed documentation changes."
    value: ${{ steps.parse.outputs.changes_committed }}
  updated_files:
    description: "JSON array of documentation files that Codex touched."
    value: ${{ steps.parse.outputs.updated_files }}
  follow_ups:
    description: "JSON array describing additional doc work, if any."
    value: ${{ steps.parse.outputs.follow_ups }}
runs:
  using: "composite"
  steps:
    - name: Run Codex doc sync
      uses: activadee/codex-action@main
      with:
        codex-auth-json-b64: ${{ inputs.codex-auth-json-b64 }}
        prompt-file: ${{ inputs.prompt-path }}
        output-file: ${{ inputs.output-path }}
        output-schema: ${{ inputs.output-schema }}
        safety-strategy: ${{ inputs.safety-strategy }}
        model: ${{ inputs.model }}
        effort: ${{ inputs.effort }}
        codex-args: ${{ inputs.codex-args }}
        pass-through-env: ${{ inputs.pass-through-env }}

    - id: parse
      name: Parse Codex response
      shell: bash
      env:
        OUTPUT_PATH: ${{ inputs.output-path }}
      run: |
        set -euo pipefail
        if [ ! -f "$OUTPUT_PATH" ]; then
          echo "::error::Missing Codex output at $OUTPUT_PATH" >&2
          exit 1
        fi
        summary=$(jq -r '.summary // ""' "$OUTPUT_PATH")
        committed=$(jq -r '.changes_committed // false' "$OUTPUT_PATH")
        updated=$(jq -c '.updated_files // []' "$OUTPUT_PATH")
        followups=$(jq -c '.follow_ups // []' "$OUTPUT_PATH")

        {
          echo "summary<<EOF"
          printf '%s\n' "$summary"
          echo "EOF"
          echo "changes_committed=$committed"
          echo "updated_files=$updated"
          echo "follow_ups=$followups"
        } >> "$GITHUB_OUTPUT"
