name: "Run Codex doc-sync edits"
description: "Invoke Codex to edit documentation, then capture the diff as a patch."
inputs:
  codex_auth_json_b64:
    description: "Base64-encoded Codex auth.json"
    required: true
  prompt_path:
    description: "Path to the prepared prompt file"
    required: true
  doc_report_path:
    description: "Path to the Markdown summary Codex must write"
    required: true
  doc_globs_file:
    description: "File containing doc glob patterns"
    required: true
  doc_patch_file:
    description: "File where the git binary diff will be stored"
    required: true
  doc_files_file:
    description: "File where the list of touched docs will be written"
    required: true
  base_ref:
    description: "Base branch reference"
    required: true
  head_ref:
    description: "Head branch reference"
    required: true
  head_sha:
    description: "Head commit SHA"
    required: true
  pr_number:
    description: "Pull request number"
    required: true
  repository:
    description: "owner/repo string"
    required: true
  safety_strategy:
    description: "Safety strategy for Codex"
    required: false
    default: drop-sudo
  model:
    description: "Codex model override"
    required: false
    default: ""
  effort:
    description: "Codex reasoning effort"
    required: false
    default: ""
  codex_args:
    description: "Extra Codex CLI arguments"
    required: false
    default: ""
outputs:
  changed:
    description: "Whether documentation files were modified"
    value: ${{ steps.detect.outputs.changed }}
runs:
  using: "composite"
  steps:
    - name: Run Codex doc sync
      uses: activadee/codex-action@main
      env:
        DOC_REPORT_PATH: ${{ inputs.doc_report_path }}
        DOC_BASE_REF: ${{ inputs.base_ref }}
        DOC_HEAD_REF: ${{ inputs.head_ref }}
        DOC_HEAD_SHA: ${{ inputs.head_sha }}
        DOC_PR_NUMBER: ${{ inputs.pr_number }}
        DOC_REPOSITORY: ${{ inputs.repository }}
      with:
        codex-auth-json-b64: ${{ inputs.codex_auth_json_b64 }}
        prompt-file: ${{ inputs.prompt_path }}
        safety-strategy: ${{ inputs.safety_strategy }}
        model: ${{ inputs.model }}
        effort: ${{ inputs.effort }}
        codex-args: ${{ inputs.codex_args }}
        sandbox-mode: danger-full-access

    - name: Verify documentation-only changes
      shell: bash
      env:
        ACTION_ROOT: ${{ github.action_path }}
        DOC_GLOBS_FILE: ${{ inputs.doc_globs_file }}
      run: |
        node "$ACTION_ROOT/../lib/verify_doc_changes.js" "$DOC_GLOBS_FILE"

    - name: Detect documentation changes
      id: detect
      shell: bash
      run: |
        if git diff --quiet; then
          echo "changed=false" >> "$GITHUB_OUTPUT"
        else
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Record doc diff
      if: steps.detect.outputs.changed == 'true'
      shell: bash
      env:
        DOC_PATCH_FILE: ${{ inputs.doc_patch_file }}
        DOC_FILES_FILE: ${{ inputs.doc_files_file }}
      run: |
        git diff --name-only > "$DOC_FILES_FILE"
        git diff --binary > "$DOC_PATCH_FILE"
